/* ferrite-sdk C bindings — generated by cbindgen, do not edit */
#ifndef FERRITE_SDK_H
#define FERRITE_SDK_H

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>


#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Error codes returned by all FFI functions.
 */
enum ferrite_error_t {
  FERRITE_ERROR_T_OK = 0,
  FERRITE_ERROR_T_NOT_INITIALIZED = -1,
  FERRITE_ERROR_T_ALREADY_INIT = -2,
  FERRITE_ERROR_T_BUFFER_FULL = -3,
  FERRITE_ERROR_T_KEY_TOO_LONG = -4,
  FERRITE_ERROR_T_NULL_PTR = -5,
  FERRITE_ERROR_T_ENCODING = -6,
  FERRITE_ERROR_T_TRANSPORT = -7,
};
typedef int32_t ferrite_error_t;

/**
 * A valid RAM address range for fault-handler stack snapshot validation.
 */
typedef struct {
  uint32_t start;
  uint32_t end;
} ferrite_ram_region_t;

/**
 * C-visible fault record returned by `ferrite_last_fault`.
 */
typedef struct {
  /**
   * `true` if a valid fault was present.
   */
  bool valid;
  /**
   * Fault type (0 = HardFault, 1 = MemFault, 2 = BusFault, 3 = UsageFault).
   */
  uint8_t fault_type;
  uint8_t _pad[2];
  /**
   * Hardware exception frame registers.
   */
  uint32_t r0;
  uint32_t r1;
  uint32_t r2;
  uint32_t r3;
  uint32_t r12;
  uint32_t lr;
  uint32_t pc;
  uint32_t xpsr;
  /**
   * Extended (software-captured) registers.
   */
  uint32_t r4;
  uint32_t r5;
  uint32_t r6;
  uint32_t r7;
  uint32_t r8;
  uint32_t r9;
  uint32_t r10;
  uint32_t r11;
  uint32_t sp;
  /**
   * First 16 words above SP at fault time.
   */
  uint32_t stack_snapshot[16];
  /**
   * Cortex-M fault status registers.
   */
  uint32_t cfsr;
  uint32_t hfsr;
  uint32_t mmfar;
  uint32_t bfar;
} ferrite_fault_record_t;

/**
 * Callback to send a single chunk.
 * `data` points to chunk bytes, `len` is the byte count.
 * Returns 0 on success, non-zero on error.
 */
typedef int32_t (*IotaiSendChunkFn)(const uint8_t *data, uint32_t len, void *ctx);

/**
 * Callback to query transport availability.
 * Returns `true` (non-zero) if the link is ready.
 */
typedef bool (*IotaiIsAvailableFn)(void *ctx);

/**
 * Transport descriptor passed from C.
 * The caller owns the `ctx` pointer and the function pointers must remain
 * valid for the duration of any `ferrite_upload` call.
 */
typedef struct {
  /**
   * Required: sends a single chunk.  Returns 0 on success.
   */
  IotaiSendChunkFn send_chunk;
  /**
   * Optional: returns whether the transport is available.
   * If NULL the transport is assumed to always be available.
   */
  IotaiIsAvailableFn is_available;
  /**
   * Opaque context pointer forwarded to every callback.
   */
  void *ctx;
} ferrite_transport_t;

/**
 * Statistics returned by `ferrite_upload`.
 */
typedef struct {
  uint32_t chunks_sent;
  uint32_t bytes_sent;
  bool fault_uploaded;
  uint32_t metrics_uploaded;
  uint32_t trace_bytes_uploaded;
} ferrite_upload_stats_t;

/**
 * Initialise the SDK.
 *
 * # Parameters
 * * `device_id`        – NUL-terminated device identifier.
 * * `firmware_version` – NUL-terminated firmware version string.
 * * `build_id`         – First 8 bytes of the ELF `.build_id`.
 * * `ticks_fn`         – Function returning the current monotonic tick count.
 * * `ram_regions`      – Pointer to an array of `IotaiRamRegion`.
 * * `ram_region_count` – Number of elements in the array.
 *
 * Returns `IotaiError::Ok` on success.
 */
ferrite_error_t ferrite_sdk_init(const char *device_id,
                                 const char *firmware_version,
                                 uint64_t build_id,
                                 uint64_t (*ticks_fn)(void),
                                 const ferrite_ram_region_t *ram_regions,
                                 uint32_t ram_region_count);

/**
 * Record the reboot reason for the current boot cycle.
 *
 * `reason` maps to `RebootReason` discriminants (0 = Unknown, 1 = PowerOnReset, ...).
 */
ferrite_error_t ferrite_record_reboot_reason(uint8_t reason);

/**
 * Retrieve the reboot reason recorded by the previous boot.
 *
 * On success the reason discriminant is written to `*out_reason` and
 * `IotaiError::Ok` is returned.  If no valid record exists the function
 * still returns `Ok` but writes `0` (Unknown).
 */
ferrite_error_t ferrite_last_reboot_reason(uint8_t *out_reason);

/**
 * Increment a counter metric by `delta`.
 *
 * `key` is a NUL-terminated C string (max 32 characters).
 */
ferrite_error_t ferrite_metric_increment(const char *key, uint32_t delta);

/**
 * Set a gauge metric to `value`.
 *
 * `key` is a NUL-terminated C string (max 32 characters).
 */
ferrite_error_t ferrite_metric_gauge(const char *key, float value);

/**
 * Record a histogram observation for `key`.
 *
 * `key` is a NUL-terminated C string (max 32 characters).
 */
ferrite_error_t ferrite_metric_observe(const char *key, float value);

/**
 * Retrieve the fault record from the previous boot.
 *
 * The fault record is written to `*out`.  If no valid fault is present
 * `out->valid` will be `false`.
 */
ferrite_error_t ferrite_last_fault(ferrite_fault_record_t *out);

/**
 * Run a full blocking upload session using the provided transport.
 *
 * On success, upload statistics are written to `*out_stats` (may be NULL if
 * the caller does not need them).
 *
 * On transport error `IotaiError::Transport` is returned and buffered data
 * is retained for the next attempt.
 */
ferrite_error_t ferrite_upload(const ferrite_transport_t *transport,
                               ferrite_upload_stats_t *out_stats);

#endif /* FERRITE_SDK_H */
